FROM python:3.10-slim-bullseye

ARG CACHE_BUST=1

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Upgrade pip tooling
RUN python -m pip install --upgrade pip setuptools wheel

# System dependencies
RUN apt-get update && \
    apt-get install -y \
        libgl1-mesa-glx \
        protobuf-compiler \
        libprotobuf-dev \
        libglib2.0-0 \
        libgomp1 \
        gcc \
        g++ \
        curl \
        libturbojpeg0 \
        git && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements first for Docker layer caching
COPY requirements.txt .

# Install Python dependencies
RUN python -m pip install numpy==1.24.4
RUN python -m pip install Cython==0.29.36
RUN python -m pip install --no-cache-dir --no-build-isolation -r requirements.txt

# Copy full application
COPY . .

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Start app via entrypoint
ENTRYPOINT ["/entrypoint.sh"]
