FROM python:3.8
ARG CACHE_BUST=1
RUN python -m pip install --upgrade pip setuptools wheel
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && \
    apt-get install -y \
        libgl1-mesa-glx \
        protobuf-compiler \
        libprotobuf-dev \
        libb64-0d \
        libglib2.0-0 \
        libgomp1 \
        gcc \
        curl \
        libturbojpeg0 \
        git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python -m pip install --no-cache-dir --no-build-isolation -r requirements.txt
