FROM python:3.10-slim-bullseye
ARG CACHE_BUST=1
RUN python -m pip install --upgrade pip setuptools wheel
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && \
    apt-get install -y \
    libgl1-mesa-glx \
    protobuf-compiler \
    libprotobuf-dev \
    libbb64-0d \
    libglib2.0-0 \
    libgomp1 \
    gcc \
    g++ \
    curl \
    libturbojpeg0 \
    git && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN python -m pip install numpy==1.24.4
RUN python -m pip install Cython==0.29.36
RUN python -m pip install --no-cache-dir --no-build-isolation -r requirements.txt
